### ISSUE TITLE
npm run build hangs on 95% emitting

### ISSUE THREAD

**Issue by Kvietinis** [antonybudianto/angular-webpack-starter#114] opened 2016-12-30 15:04 UTC
I'm not sure if this an issue here or somewhere on my side but I'm just out of ideas. Doesn't work on current version from master nor the version from RC. Any ideas?

**Comment by antonybudianto** [comment] 2016-12-30 15:20
Duplicate of #102 , #74 

For short, this is `ngtools/webpack` issue

**Closed by antonybudianto** 2016-12-30 15:20 UTC
