### ISSUE TITLE
Build stuck at 95%

### ISSUE THREAD

**Issue by unsafecode** [antonybudianto/angular-webpack-starter#74] opened 2016-11-11 08:45 UTC
## Issue Overview
When building, the compilation stops at "95% emitting".

## Issue Description
When building, the compilation stops at "95% emitting" and hangs. However, even killing the process makes the files to be outputted to the `dist` directory.

## Reproducables
Clone the repo and run `npm run build`

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	|Windows 10 v.1607 	|
| **Node version**     	| 6.9.1   	|
| **NPM Version**      	| 3.10.8    	|
| **Environment**       | Browser          |

**Comment by antonybudianto7** [comment] 2016-11-11 09:12
any reproducable?

**Comment by antonybudianto** [comment] 2016-11-13 15:05
Please follow it there https://github.com/angular/angular-cli/issues/3019

**Comment by antonybudianto7** [comment] 2016-11-22 06:15
closing as no feedback

**Closed by antonybudianto7** 2016-11-22 06:15 UTC
Labels: not-reproducable

**Comment by laimonas** [comment] 2016-12-01 10:09
With latest sources for me "npm run build" also always stuck on 95%. Environment is the same as in issue description. Also when "npm start" is also not working, just showing empty webpack dashboard.

**Comment by antonybudianto7** [comment] 2016-12-01 10:24
@laimonas , yes, it's now tracked on angular-cli repo

**Comment by laimonas** [comment] 2016-12-30 15:36
Commenting devtool: 'source-map' line in webpack.dev.js solve this problem for me on windows. On linux i cannot reproduce this.

**Comment by antonybudianto** [comment] 2016-12-30 16:18
For windows users, please use `npm run build:jit` temporarily
