### ISSUE TITLE
npm run build on Ubuntu

### ISSUE THREAD

**Issue by kurigohan** [antonybudianto/angular-webpack-starter#129] opened 2017-02-27 21:39 UTC
## Issue Overview
I am running into an issue with `npm run build`. The command works fine on OSX, but when I attempt to run the command on Ubuntu, I am getting an error. I think it might be a path issue but I'm not sure how to proceed. Any ideas?

## Issue Description
<pre>

 10% building modules 0/4 modules 4 active ...index.js!/var/www/mda/web/src/main.tsno-unused-variable is deprecated. Use the tsc compiler options --noUnusedParameters and --noUnusedLocals instead.
 10% building modules 4/4 modules 0 activeModuleNotFoundError: Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/mda/web/src'
    at factoryCallback (/var/www/mda/web/node_modules/webpack/lib/Compilation.js:230:39)
    at /var/www/mda/web/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/var/www/mda/web/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /var/www/mda/web/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:933:13)
    at /var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:843:16
    at /var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /var/www/mda/web/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at /var/www/mda/web/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/var/www/mda/web/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /var/www/mda/web/node_modules/tapable/lib/Tapable.js:283:15
    at /var/www/mda/web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/var/www/mda/web/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /var/www/mda/web/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/var/www/mda/web/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/var/www/mda/web/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/mda/web/src'
  using description file: /var/www/mda/web/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /var/www/mda/web/package.json (relative path: ./src)
    using description file: /var/www/mda/web/package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      as directory
        /var/www/mda/web/src/$$_gendir/app/app.module.ngfactory doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/mda/web/src/$$_gendir/app/app.module.ngfactory doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/mda/web/src/$$_gendir/app/app.module.ngfactory.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/mda/web/src/$$_gendir/app/app.module.ngfactory.ts doesn't exist

</pre>

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Ubuntu 16.04 |
| **Node version**     	| 6.10.0  	|
| **NPM Version**      	| 3.10.10	|

**Comment by antonybudianto** [comment] 2017-02-28 00:01
are you sure your npm version is correct?

**Comment by kurigohan** [comment] 2017-02-28 16:21
Sorry, I listed the NVM version. NPM version is 3.10. I updated the issue.

**Comment by antonybudianto** [comment] 2017-03-04 10:01
can you try on latest master? @kurigohan

**Comment by kurigohan** [comment] 2017-03-06 01:53
I updated to master and I'm still getting the same error. This error only occurs for the AOT build. JIT works fine, even before updating to master.

**Comment by antonybudianto** [comment] 2017-03-06 12:09
Just tried on Ubuntu machine, still cannot reproduce 😕

**Comment by antonybudianto** [comment] 2017-03-21 15:25
closing this since it's not reproducible on my side, feel free to reopen if you've reproducible.

**Closed by antonybudianto** 2017-03-21 15:25 UTC
